iri: 7992a208-90d6-4bfc-a4b9-ecd365eac917
projectIri: 7992a208-90d6-4bfc-a4b9-ecd365eac917
types:
  - http://dataspecer.com/resources/local/package
userMetadata:
  label: {}
  description: {}
metadata:
  creationDate: 2026-04-09T16:09:02.437Z
  modificationDate: 2026-04-09T16:09:17.021Z
_version: 1
_exportVersion: 2
_exportedAt: 2026-04-09T16:09:22.756Z
_exportedBy: http://localhost:3100
